platform :ios, '15.0'

project 'LanbridgeIOS.xcodeproj', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

flutter_application_path = '../mobile-flutter'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'Lanbridge' do
  install_all_flutter_pods(flutter_application_path)
end

post_install do |installer|
  flutter_post_install(installer) if defined?(flutter_post_install)
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      # Xcode 27 已不再支持 iOS 15 以下的模拟器目标，统一覆盖插件默认值。
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
    end
  end
end
